[features]
seeds = false
skip-lint = false
[programs.localnet]
gdupgrader = "7zytPdaZiXNjYQh1cStfAcFws7ZRhSLtUfhdoev9vp5G"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "localnet"
cluster = "devnet"
wallet = "/home/alphaprime8/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
